In [18]:
#includes
import numpy as np
from collections import Counter
import pandas as pd
import os
import PIL.Image

In [20]:
#to check how much did algo predict right
def accuracy(y_tes, y_pred):
    correct = 0
    for i in range(len(y_pred)):
        if(y_tes[i] == y_pred[i]):
            correct += 1
    return (correct/len(y_tes))*100

In [21]:
dataset = pd.read_csv('breastCancer.csv')
dataset.head()

id  clump_thickness  size_uniformity  shape_uniformity  \
0  1000025                5                1                 1   
1  1002945                5                4                 4   
2  1015425                3                1                 1   
3  1016277                6                8                 8   
4  1017023                4                1                 1   

   marginal_adhesion  epithelial_size bare_nucleoli  bland_chromatin  \
0                  1                2             1                3   
1                  5                7            10                3   
2                  1                2             2                3   
3                  1                3             4                3   
4                  3                2             1                3   

   normal_nucleoli  mitoses  class  
0                1        1      2  
1                2        1      2  
2                1        1      2  
3                7        1      2  
4                1        1      2

In [32]:
def run():
    # Importing the dataset
    dataset = pd.read_csv('breastCancer.csv')
    dataset.replace('?', -9999, inplace=True)
    dataset = dataset.applymap(np.int64)
    X = dataset.iloc[:, 1:-1].values
    y = dataset.iloc[:, -1].values
    
    # Splitting the dataset into the Training set and Test set
    from sklearn.cross_validation import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

    # Feature Scaling
#     from sklearn.preprocessing import StandardScaler
#     sc = StandardScaler()
#     X_train = sc.fit_transform(X_train)
#     X_test = sc.transform(X_test)
    
    classifier = KNeighborsClassifieR()
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
#     print("My KNN accuracy: ",accuracy(y_test, y_pred),'%')
    

In [33]:
run()

In [34]:
def skLearnKNN():
    # Importing the dataset
    dataset = pd.read_csv('breastCancer.csv')
    dataset.replace('?', 0, inplace=True)
    dataset = dataset.applymap(np.int64)
    X = dataset.iloc[:, 1:-1].values
    y = dataset.iloc[:, -1].values
    
    # Splitting the dataset into the Training set and Test set
    from sklearn.cross_validation import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

    # Feature Scaling
#     from sklearn.preprocessing import StandardScaler
#     sc = StandardScaler()
#     X_train = sc.fit_transform(X_train)
#     X_test = sc.transform(X_test)
    print(X_train[:10])
    print(X_test[:10])
    
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier()
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
#     print("Sklearn accuracy: ", accuracy(y_test, y_pred),'%')

In [35]:
skLearnKNN()

[[ 8 10  4  4  8 10  8  2  1]
 [ 3  1  2  1  2  1  2  1  1]
 [ 8 10 10 10  7  5  4  8  7]
 [ 6  6  7 10  3 10  8 10  2]
 [ 4  1  1  1  2  3  2  1  1]
 [ 5  5  5  6  3 10  3  1  1]
 [ 4  6  5  6  7  0  4  9  1]
 [10 10 10 10  3 10 10  6  1]
 [ 5  1  1  1  2  1  1  1  1]
 [ 1  2  1  3  2  1  1  2  1]]
[[ 4  1  2  1  2  1  1  1  1]
 [ 4  2  2  1  2  1  2  1  1]
 [ 6  6  6  9  6  0  7  8  1]
 [ 5  1  1  1  2  1  2  2  1]
 [ 8  7  5 10  7  9  5  5  4]
 [ 2  1  1  1  2  1  3  1  1]
 [10 10  6  3  3 10  4  3  2]
 [ 2  1  1  1  2  1  3  1  1]
 [10  4  4 10  2 10  5  3  3]
 [ 8  2  3  1  6  3  7  1  1]]


In [36]:
#knn class
class KNeighborsClassifieR(object):

	def __init__(self):
		pass
    #"training" function
	def fit(self, X, y):
		self.X_train = X
		self.y_train = y

    #predict function, output of this function is lis to
	def predict(self, X_test, k=5):
		distances = self.compute_distances(self.X_train, X_test)
		vote_results = []
		for i in range(len(distances)):
			votesOneSample = []
			for j in range(k):
				votesOneSample.append(distances[i][j][1])
			vote_results.append(Counter(votesOneSample).most_common(1)[0][0])
		
		return vote_results
    

	#For each sample and every item in test set algorithm is making tuple in distance list
	#this is how list looks =>> distances = [[[distance, class],[distance, class],[distance, class],[distance, class]]]
	#distances and sort
	def compute_distances(self, X, X_test):
		distances = []
		for i in range(X_test.shape[0]):
			euclidian_distances = np.zeros(X.shape[0])
			oneSampleList = []
			for j in range(len(X)):
				euclidian_distances[j] = np.sqrt(np.sum(np.square(np.array(X_test[i]) - np.array(X[j]))))
				oneSampleList.append([euclidian_distances[j], self.y_train[j]])
			#drugi deo je klasa za element iz train seta za koji smo racunali u ovom krugu
			distances.append(sorted(oneSampleList))
		return distances
